FROM node:22-alpine AS builder

WORKDIR /app

# Dependências necessárias para compilar módulos nativos
RUN apk add --no-cache \
    python3 \
    make \
    g++
COPY package*.json ./

RUN npm ci

COPY . .

RUN npx expo export --platform web


# =========================
# Stage 2 - Nginx
# =========================
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
